M48
; DRILL file {KiCad (6.0.7)} date Wed Oct 26 04:57:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-26T04:57:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.2837Y-2.3703
X4.2837Y-4.2994
X6.5672Y-2.3703
X6.5672Y-4.2994
T0
M30
